package seabattleshared;

public enum WebSocketType {
    REGISTER,
    REGISTERPLAYER,
    REGISTEROPPONENT,
    ERROR,
    FATALERROR,
    PLACESHIP,
    REMOVESHIP,
    SETSQUAREPLAYER,
    CHECKOVERLAP,
    REMOVEALLSHIPS,
    READY,
    STARTGAME,
}
