package seabattleshared;

public enum WebSocketType {
    REGISTER,
    REGISTERPLAYER,
    REGISTEROPPONENT,
    ERROR,
    FATALERROR,
    PLACESHIP,
    REMOVESHIP,
    REMOVEALLSHIPS,
    SETSQUAREPLAYER,
    SETSQUAREOPPONENT,
    CHECKOVERLAP,
    READY,
    STARTGAME,
    FIRESHOT,
    PLAYERSHOT,
    OPPONENTSHOT,
}
